### ISSUE TITLE
How to test ?

### ISSUE THREAD

**Issue by XZNWU** [shekkizh/FCN.tensorflow#76] opened 2017-12-15 13:28 UTC
I have completed the train . but I just want to test an image, and get a segmentation image, how to achieve?

**Comment by wxwhu** [comment] 2017-12-16 08:36
hello
   I'm sorry to bother you,can you tell me what's your tensorflow version.I downloaded this code,but I met a promblem like this,but I don't know the cause .
![reason](https://user-images.githubusercontent.com/32167040/34068891-45164ff0-e27f-11e7-8e3e-bf80f9dd69c7.png)

**Comment by yyong119** [comment] 2018-02-01 01:56
@wxwhu I met it too at first. It turned out that I was reading the dataset in a wrong way(I changed the dataset to LSUN dataset). BTW, tf version 1.1.0.

**Comment by siddharthamantrala** [comment] 2018-02-20 13:14
@yyong119  Hey, even I got the same error @wxwhu got. I ran the code on Windows 8.1. Can you help me in resolving the error? 
Thanks,
Siddhartha

**Comment by ahnHeejune** [comment] 2018-03-24 16:13
The reason you got input of shape (0, ) is because you did not get any image in dataset.  The original code assume you use Linux system so the path separator is "/" not "\\" (  filename = os.path.splitext(f.split("/")[-1])[0] )   in read_MITSceneParsingData.py.

**Comment by ahnHeejune** [comment] 2018-03-24 16:15
@yyong119   Hello, did you get successful segmentation performance with this code after you fixed the data set problem?  In my case, the  loss doesnot decrease from 3 or 4.  Please Let me know it

**Comment by shekkizh** [comment] 2018-05-18 15:16
Closing due to inactivity. Answered in other issues.

**Closed as completed by shekkizh** 2018-05-18 15:16 UTC
